FROM node:20 AS react-build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
ENV REACT_APP_NAME=Sebastian
RUN npm run build

FROM nginx:stable
COPY --from=react-build /app/build /usr/...
